"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { usePathname } from "next/navigation";

import { ChakraProvider, CSSReset } from "@chakra-ui/react";
import ReduxProvider from "@/app/components/providers/ReduxProvider";

import { checkIsPublicRoute } from "@/utils/checkIsPublicRoute";
import { PrivateRouter } from "@/app/components/privateRouter/privateRouter";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isPublic = checkIsPublicRoute(pathname);

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&family=Nunito:wght@400;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <CSSReset />
        <ChakraProvider>
          <ReduxProvider>
            {isPublic && children}

            {!isPublic && <PrivateRouter>{children}</PrivateRouter>}
          </ReduxProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
